// ============================================================
// Operation Epic Fury — Information Domain Scenario Data
// ============================================================

import { Claim, Narrative, BotNetwork, InfoFogZone } from './types';

// ============================================================
// CLAIMS — 15 entries covering the 3-day timeline
// ============================================================

export const EPIC_FURY_CLAIMS: Claim[] = [

  // --- H-Hour: First claims emerge ---
  {
    id: 'CLM-001',
    scenarioId: 'epic-fury',
    headline: 'IRNA: Explosion at Isfahan chemical plant — no nuclear connection',
    body: 'Iranian state news agency IRNA reports explosions at what it describes as a petrochemical storage facility near Isfahan. The report explicitly denies any connection to nuclear facilities and attributes the explosion to an industrial accident. No mention of military activity.',
    mediaType: 'article',
    infoEventType: 'disinfo_state',
    misinfoTaxonomy: ['fabrication', 'misleading_framing'],
    truthScore: 8,
    severityTier: 'critical',
    origin: { lat: 35.6892, lon: 51.3890 },
    targetLocation: { lat: 32.6546, lon: 51.6680 },
    propagationRadius: 500,
    timestamp: '2026-02-28T02:20:00Z',
    peakTimestamp: '2026-02-28T04:00:00Z',
    source: {
      name: 'IRNA',
      type: 'state_media',
      country: 'IR',
      credibilityRating: 15,
      isStateAffiliated: true,
      platform: 'website',
      knownFor: 'Islamic Republic News Agency — official Iranian state news',
    },
    amplifiers: [
      {
        name: 'PressTV',
        type: 'state_media',
        platform: 'twitter',
        followerCount: 850000,
        amplifiedAt: '2026-02-28T02:25:00Z',
        isBotSuspected: false,
        amplificationMethod: 'repost',
      },
      {
        name: '@truth_seeker_2024',
        type: 'anonymous_account',
        platform: 'twitter',
        followerCount: 45000,
        amplifiedAt: '2026-02-28T02:32:00Z',
        location: { lat: 55.7558, lon: 37.6173 },
        isBotSuspected: true,
        amplificationMethod: 'quote',
      },
    ],
    linkedGroundTruthEventId: 'K-003',
    propagation: {
      speed: 'explosive',
      pattern: 'state_broadcast',
      peakVelocity: 12000,
      halfLife: 8,
      crossPlatformHops: 4,
    },
    reach: {
      estimatedImpressions: 45000000,
      shares: 180000,
      engagementRate: 0.04,
      countriesReached: ['IR', 'IQ', 'SY', 'LB', 'RU', 'CN', 'PK'],
      languagesSpread: ['fa', 'ar', 'ru', 'en'],
    },
    verificationStatus: 'debunked',
    groundTruthSummary: 'The explosion was a precision-guided munition strike on the Natanz uranium enrichment facility, confirmed by satellite imagery and US DoD statement. No chemical plant exists at the target coordinates.',
    evidenceLinks: [
      {
        url: 'pentagon.mil/press-release-028',
        title: 'DoD confirms strikes on Iranian nuclear facilities',
        sourceReliability: 85,
        verdict: 'refutes',
        snippet: 'US Central Command confirmed precision strikes against four Iranian nuclear facilities including Natanz.',
      },
      {
        url: 'planet.com/imagery/isfahan-028',
        title: 'Satellite imagery — Isfahan/Natanz 28 Feb 2026',
        sourceReliability: 95,
        verdict: 'refutes',
        snippet: 'Before/after imagery shows destruction consistent with military strike at known Natanz enrichment facility coordinates.',
      },
    ],
  },

  // CLM-002: US DoD official statement
  {
    id: 'CLM-002',
    scenarioId: 'epic-fury',
    headline: 'Pentagon: Precision strikes neutralized Iranian nuclear weapons infrastructure',
    body: 'US Department of Defense confirms Operation Epic Fury targeted four nuclear enrichment and weapons research facilities. Statement emphasizes no civilian targets were struck and all munitions were precision-guided.',
    mediaType: 'official',
    infoEventType: 'verification',
    misinfoTaxonomy: ['cherry_picked'],
    truthScore: 75,
    severityTier: 'benign',
    origin: { lat: 38.8711, lon: -77.0559 },
    targetLocation: { lat: 33.72, lon: 51.73 },
    propagationRadius: 2000,
    timestamp: '2026-02-28T03:00:00Z',
    peakTimestamp: '2026-02-28T06:00:00Z',
    source: {
      name: 'US Department of Defense',
      type: 'state_official',
      country: 'US',
      credibilityRating: 70,
      isStateAffiliated: true,
      platform: 'website',
      knownFor: 'Pentagon official press releases',
    },
    amplifiers: [
      {
        name: 'AP News',
        type: 'wire_service',
        platform: 'twitter',
        followerCount: 15000000,
        amplifiedAt: '2026-02-28T03:05:00Z',
        isBotSuspected: false,
        amplificationMethod: 'repost',
      },
    ],
    linkedGroundTruthEventId: 'K-002',
    propagation: {
      speed: 'explosive',
      pattern: 'state_broadcast',
      peakVelocity: 50000,
      halfLife: 24,
      crossPlatformHops: 6,
    },
    reach: {
      estimatedImpressions: 200000000,
      shares: 500000,
      engagementRate: 0.03,
      countriesReached: ['US', 'GB', 'FR', 'DE', 'JP', 'AU', 'CA', 'IL'],
      languagesSpread: ['en', 'fr', 'de', 'ja'],
    },
    verificationStatus: 'partly_true',
    groundTruthSummary: 'Strikes confirmed by multiple sources. However, statement omits collateral damage to Isfahan hospital and the targeted assassination of Supreme Leader Khamenei, framing the operation as purely counter-proliferation.',
    evidenceLinks: [
      {
        url: 'reuters.com/iran-strikes-confirmed',
        title: 'Reuters confirms four nuclear sites struck',
        sourceReliability: 92,
        verdict: 'supports',
        snippet: 'Independent reporting confirms strikes at Natanz, Isfahan, Fordow, and Parchin facilities.',
      },
    ],
  },

  // CLM-003: IRGC claims air defense success
  {
    id: 'CLM-003',
    scenarioId: 'epic-fury',
    headline: 'IRGC: Air defenses shot down 80% of incoming missiles — victory for Iran',
    body: 'Islamic Revolutionary Guard Corps claims Bavar-373 and S-300 systems intercepted the majority of US/Israeli missiles. Video released purportedly showing missile interceptions over Tehran.',
    mediaType: 'broadcast',
    infoEventType: 'disinfo_state',
    misinfoTaxonomy: ['fabrication', 'misleading_framing', 'emotional_manipulation'],
    truthScore: 12,
    severityTier: 'high',
    origin: { lat: 35.6892, lon: 51.3890 },
    propagationRadius: 600,
    timestamp: '2026-02-28T04:30:00Z',
    peakTimestamp: '2026-02-28T08:00:00Z',
    source: {
      name: 'IRGC Media Bureau',
      type: 'state_official',
      country: 'IR',
      credibilityRating: 10,
      isStateAffiliated: true,
      platform: 'telegram',
      knownFor: 'IRGC official communications channel',
    },
    amplifiers: [
      {
        name: '@resist_imperialism',
        type: 'anonymous_account',
        platform: 'twitter',
        followerCount: 120000,
        amplifiedAt: '2026-02-28T04:45:00Z',
        location: { lat: 33.31, lon: 44.37 },
        isBotSuspected: true,
        amplificationMethod: 'quote',
      },
    ],
    linkedGroundTruthEventId: 'K-001',
    propagation: {
      speed: 'fast',
      pattern: 'state_broadcast',
      peakVelocity: 8000,
      halfLife: 6,
      crossPlatformHops: 3,
    },
    reach: {
      estimatedImpressions: 35000000,
      shares: 140000,
      engagementRate: 0.05,
      countriesReached: ['IR', 'IQ', 'SY', 'LB', 'YE', 'RU'],
      languagesSpread: ['fa', 'ar', 'ru'],
    },
    verificationStatus: 'debunked',
    groundTruthSummary: 'US CENTCOM confirmed all targets struck successfully. Satellite imagery of all four nuclear sites shows complete destruction. Iranian air defense was suppressed in opening SEAD salvo. Released video is from 2024 Iranian air defense drill.',
    evidenceLinks: [
      {
        url: 'centcom.mil/operation-epic-fury-bda',
        title: 'CENTCOM: All strike objectives achieved',
        sourceReliability: 80,
        verdict: 'refutes',
        snippet: 'Battle damage assessment confirms all primary and secondary targets neutralized.',
      },
    ],
  },

  // CLM-004: Al Jazeera fact-based report
  {
    id: 'CLM-004',
    scenarioId: 'epic-fury',
    headline: 'Al Jazeera: Multiple explosions across Iran — nuclear sites appear targeted',
    body: 'Al Jazeera correspondents report large explosions near known nuclear facilities at Isfahan, Natanz, and Fordow. Sources describe coordinated strikes beginning around 02:15 UTC. No independent access to strike sites.',
    mediaType: 'broadcast',
    infoEventType: 'verification',
    misinfoTaxonomy: ['missing_context'],
    truthScore: 80,
    severityTier: 'benign',
    origin: { lat: 25.2854, lon: 51.5310 },
    targetLocation: { lat: 33.72, lon: 51.73 },
    propagationRadius: 1500,
    timestamp: '2026-02-28T02:45:00Z',
    peakTimestamp: '2026-02-28T05:00:00Z',
    source: {
      name: 'Al Jazeera',
      type: 'legacy_media',
      country: 'QA',
      credibilityRating: 65,
      isStateAffiliated: false,
      platform: 'tv',
      knownFor: 'Qatar-based international news network',
    },
    amplifiers: [],
    linkedGroundTruthEventId: 'K-002',
    propagation: {
      speed: 'explosive',
      pattern: 'influencer_cascade',
      peakVelocity: 30000,
      halfLife: 12,
      crossPlatformHops: 5,
    },
    reach: {
      estimatedImpressions: 120000000,
      shares: 280000,
      engagementRate: 0.03,
      countriesReached: ['QA', 'SA', 'AE', 'EG', 'GB', 'US'],
      languagesSpread: ['ar', 'en'],
    },
    verificationStatus: 'confirmed',
    groundTruthSummary: 'Accurate reporting of strike locations and timing. Missing context: did not report the assassination of Supreme Leader Khamenei which was not publicly confirmed for several hours.',
    evidenceLinks: [],
  },

  // CLM-005: Iran claims Fordow was civilian research
  {
    id: 'CLM-005',
    scenarioId: 'epic-fury',
    headline: 'Iran FM: Fordow is peaceful research center — attack is war crime',
    body: 'Iranian Foreign Minister issues statement calling strikes on Fordow an attack on civilian scientists conducting peaceful nuclear research. Calls for immediate UN Security Council session.',
    mediaType: 'official',
    infoEventType: 'disinfo_state',
    misinfoTaxonomy: ['misleading_framing', 'missing_context'],
    truthScore: 15,
    severityTier: 'high',
    origin: { lat: 35.6892, lon: 51.3890 },
    targetLocation: { lat: 34.88, lon: 51.59 },
    propagationRadius: 400,
    timestamp: '2026-02-28T05:00:00Z',
    peakTimestamp: '2026-02-28T10:00:00Z',
    source: {
      name: 'Iran Foreign Ministry',
      type: 'state_official',
      country: 'IR',
      credibilityRating: 18,
      isStateAffiliated: true,
      platform: 'website',
      knownFor: 'Official Iranian government foreign policy statements',
    },
    amplifiers: [],
    linkedGroundTruthEventId: 'K-004',
    propagation: {
      speed: 'fast',
      pattern: 'state_broadcast',
      peakVelocity: 6000,
      halfLife: 10,
      crossPlatformHops: 3,
    },
    reach: {
      estimatedImpressions: 25000000,
      shares: 90000,
      engagementRate: 0.04,
      countriesReached: ['IR', 'RU', 'CN', 'VE', 'CU'],
      languagesSpread: ['fa', 'ru', 'zh', 'es'],
    },
    verificationStatus: 'debunked',
    groundTruthSummary: 'IAEA reports confirm Fordow was enriching uranium to 60% — far beyond civilian research levels. Facility was built inside a mountain specifically to survive military strikes.',
    evidenceLinks: [
      {
        url: 'iaea.org/fordow-enrichment-report',
        title: 'IAEA: Fordow enriching to 60%',
        sourceReliability: 98,
        verdict: 'refutes',
        snippet: 'Latest IAEA inspection report confirms Fordow facility enriching uranium to 60%, inconsistent with civilian research claims.',
      },
    ],
  },

  // CLM-006: Telegram rumor — US troops on ground
  {
    id: 'CLM-006',
    scenarioId: 'epic-fury',
    headline: 'BREAKING: US Marines reportedly landing on Iranian coast near Bandar Abbas',
    body: 'Unverified reports circulating on Telegram channels claim US Marine amphibious forces are conducting a beach landing near Bandar Abbas. No visual evidence provided. Multiple OSINT accounts amplifying without verification.',
    mediaType: 'telegram',
    infoEventType: 'misinfo_organic',
    misinfoTaxonomy: ['fabrication', 'emotional_manipulation'],
    truthScore: 0,
    severityTier: 'critical',
    origin: { lat: 27.18, lon: 56.27 },
    propagationRadius: 300,
    timestamp: '2026-02-28T05:30:00Z',
    peakTimestamp: '2026-02-28T07:00:00Z',
    decayTimestamp: '2026-02-28T09:00:00Z',
    source: {
      name: '@gulf_military_watch',
      type: 'anonymous_account',
      country: 'unknown',
      credibilityRating: 8,
      isStateAffiliated: false,
      platform: 'telegram',
      followerCount: 18000,
    },
    amplifiers: [
      {
        name: '@geopolitics_daily',
        type: 'influencer',
        platform: 'twitter',
        followerCount: 250000,
        amplifiedAt: '2026-02-28T05:45:00Z',
        isBotSuspected: false,
        amplificationMethod: 'quote',
      },
    ],
    propagation: {
      speed: 'explosive',
      pattern: 'organic_viral',
      peakVelocity: 15000,
      halfLife: 3,
      crossPlatformHops: 4,
    },
    reach: {
      estimatedImpressions: 30000000,
      shares: 120000,
      engagementRate: 0.07,
      countriesReached: ['US', 'GB', 'IR', 'SA', 'AE'],
      languagesSpread: ['en', 'ar', 'fa'],
    },
    verificationStatus: 'debunked',
    groundTruthSummary: 'No ground invasion occurred. Operation Epic Fury was exclusively an air/naval strike campaign. Pentagon explicitly denied any ground forces entering Iranian territory.',
    evidenceLinks: [
      {
        url: 'defense.gov/no-ground-troops',
        title: 'Pentagon: No US ground forces in Iran',
        sourceReliability: 85,
        verdict: 'refutes',
        snippet: 'DOD spokesperson categorically denied any ground force deployment to Iran.',
      },
    ],
  },

  // CLM-007: Deepfake surrender video
  {
    id: 'CLM-007',
    scenarioId: 'epic-fury',
    headline: 'Video circulating: Iranian military commander announces ceasefire',
    body: 'A video purporting to show IRGC General Hossein Salami announcing an immediate ceasefire and surrender of nuclear materials is circulating on Telegram and Twitter. The video shows signs of AI generation including inconsistent lip sync and audio artifacts.',
    mediaType: 'video',
    infoEventType: 'deepfake',
    misinfoTaxonomy: ['fabrication', 'impersonation'],
    truthScore: 0,
    severityTier: 'critical',
    origin: { lat: 32.0853, lon: 34.7818 },
    targetLocation: { lat: 35.6892, lon: 51.3890 },
    propagationRadius: 1200,
    timestamp: '2026-02-28T06:15:00Z',
    peakTimestamp: '2026-02-28T09:00:00Z',
    decayTimestamp: '2026-02-28T14:00:00Z',
    source: {
      name: '@mideast_breaking',
      type: 'anonymous_account',
      country: 'unknown',
      credibilityRating: 5,
      isStateAffiliated: false,
      platform: 'telegram',
      knownFor: 'Anonymous account, created 72 hours before conflict',
    },
    amplifiers: [],
    propagation: {
      speed: 'explosive',
      pattern: 'seeded_amplified',
      peakVelocity: 25000,
      halfLife: 4,
      crossPlatformHops: 5,
    },
    reach: {
      estimatedImpressions: 80000000,
      shares: 320000,
      engagementRate: 0.08,
      countriesReached: ['IR', 'US', 'IL', 'GB', 'DE', 'FR', 'SA', 'AE'],
      languagesSpread: ['en', 'fa', 'ar', 'he'],
    },
    verificationStatus: 'debunked',
    groundTruthSummary: 'AI-generated deepfake. IRGC issued denial via official channels. Video analysis by multiple forensic labs confirmed synthetic generation artifacts. Gen. Salami appeared on IRIB live broadcast 3 hours after video surfaced.',
    evidenceLinks: [
      {
        url: 'reuters.com/factcheck/iran-ceasefire-video',
        title: 'Fact check: Purported Iranian ceasefire video is AI-generated',
        sourceReliability: 92,
        verdict: 'refutes',
        snippet: 'Digital forensics analysis reveals inconsistent facial rendering, audio desync, and metadata indicating AI generation tools.',
      },
    ],
  },

  // CLM-008: Russia Today amplifies Iran narrative
  {
    id: 'CLM-008',
    scenarioId: 'epic-fury',
    headline: 'RT: Western aggression against Iran mirrors Iraq 2003 — no evidence of weapons program',
    body: 'Russia Today runs multi-hour special framing strikes as unprovoked aggression, comparing to Iraq WMD narrative. Features Russian military analysts questioning whether Iranian nuclear facilities actually existed.',
    mediaType: 'broadcast',
    infoEventType: 'disinfo_proxy',
    misinfoTaxonomy: ['misleading_framing', 'cherry_picked', 'appeal_to_authority'],
    truthScore: 20,
    severityTier: 'high',
    origin: { lat: 55.7558, lon: 37.6173 },
    targetLocation: { lat: 35.6892, lon: 51.3890 },
    propagationRadius: 800,
    timestamp: '2026-02-28T06:00:00Z',
    peakTimestamp: '2026-02-28T12:00:00Z',
    source: {
      name: 'RT (Russia Today)',
      type: 'state_media',
      country: 'RU',
      credibilityRating: 12,
      isStateAffiliated: true,
      platform: 'tv',
      knownFor: 'Russian state-funded international news network',
    },
    amplifiers: [
      {
        name: '@multipolar_world',
        type: 'anonymous_account',
        platform: 'twitter',
        followerCount: 85000,
        amplifiedAt: '2026-02-28T06:30:00Z',
        location: { lat: 55.75, lon: 37.62 },
        isBotSuspected: true,
        amplificationMethod: 'repost',
      },
    ],
    propagation: {
      speed: 'fast',
      pattern: 'state_broadcast',
      peakVelocity: 10000,
      halfLife: 18,
      crossPlatformHops: 4,
    },
    reach: {
      estimatedImpressions: 50000000,
      shares: 200000,
      engagementRate: 0.04,
      countriesReached: ['RU', 'DE', 'FR', 'IN', 'BR', 'ZA'],
      languagesSpread: ['ru', 'en', 'de', 'fr'],
    },
    verificationStatus: 'debunked',
    groundTruthSummary: 'IAEA has documented Iranian enrichment to 60% over multiple inspection cycles. Iran facilities were declared to IAEA. Comparison to Iraq 2003 is misleading — IAEA confirmed Iranian nuclear activity, unlike Iraq where no WMDs were found.',
    evidenceLinks: [],
  },

  // CLM-009: Correction — BBC retraction
  {
    id: 'CLM-009',
    scenarioId: 'epic-fury',
    headline: 'BBC issues correction: Earlier report of 500 civilian casualties was unverified Iranian state source',
    body: 'BBC retracts earlier reporting that cited Iranian state media casualty figures without sufficient independent verification. Updated reporting notes that independent casualty assessment is impossible due to information blackout.',
    mediaType: 'article',
    infoEventType: 'correction',
    misinfoTaxonomy: [],
    truthScore: 90,
    severityTier: 'benign',
    origin: { lat: 51.5074, lon: -0.1278 },
    propagationRadius: 1000,
    timestamp: '2026-02-28T10:00:00Z',
    source: {
      name: 'BBC News',
      type: 'legacy_media',
      country: 'GB',
      credibilityRating: 82,
      isStateAffiliated: false,
      platform: 'website',
      knownFor: 'British Broadcasting Corporation — public service broadcaster',
    },
    amplifiers: [],
    propagation: {
      speed: 'steady',
      pattern: 'influencer_cascade',
      peakVelocity: 5000,
      halfLife: 12,
      crossPlatformHops: 3,
    },
    reach: {
      estimatedImpressions: 15000000,
      shares: 45000,
      engagementRate: 0.02,
      countriesReached: ['GB', 'US', 'AU', 'CA'],
      languagesSpread: ['en'],
    },
    verificationStatus: 'confirmed',
    groundTruthSummary: 'Responsible correction. Independent casualty verification remains impossible due to Tehran information blackout. Iranian state media figures are unreliable in both directions.',
    evidenceLinks: [],
  },

  // CLM-010: Bot-amplified hashtag campaign
  {
    id: 'CLM-010',
    scenarioId: 'epic-fury',
    headline: '#StopIranGenocide trends worldwide — analysis reveals 60% bot amplification',
    body: 'The hashtag #StopIranGenocide reaches global trending within 4 hours of strikes. Bot detection services identify coordinated amplification from networks in Tehran and St. Petersburg. Genuine organic outrage mixed with artificial amplification.',
    mediaType: 'social_post',
    infoEventType: 'disinfo_amplified',
    misinfoTaxonomy: ['coordinated_amplification', 'emotional_manipulation'],
    truthScore: 25,
    severityTier: 'moderate',
    origin: { lat: 35.6892, lon: 51.3890 },
    propagationRadius: 2000,
    timestamp: '2026-02-28T06:30:00Z',
    peakTimestamp: '2026-02-28T12:00:00Z',
    source: {
      name: 'Coordinated network',
      type: 'bot_network',
      country: 'IR',
      credibilityRating: 5,
      isStateAffiliated: true,
      platform: 'twitter',
    },
    amplifiers: [],
    propagation: {
      speed: 'explosive',
      pattern: 'bot_swarm',
      peakVelocity: 40000,
      halfLife: 8,
      crossPlatformHops: 4,
    },
    reach: {
      estimatedImpressions: 150000000,
      shares: 600000,
      engagementRate: 0.06,
      countriesReached: ['US', 'GB', 'IR', 'IQ', 'RU', 'DE', 'FR', 'IN', 'PK', 'TR'],
      languagesSpread: ['en', 'fa', 'ar', 'ru', 'de', 'tr'],
    },
    verificationStatus: 'disputed',
    groundTruthSummary: 'Hashtag combines genuine anti-war sentiment with coordinated inauthentic amplification. The term "genocide" is inaccurate — strikes targeted military/nuclear infrastructure, not civilian populations, though collateral damage occurred.',
    evidenceLinks: [],
  },

  // CLM-011: Hormuz mine claim
  {
    id: 'CLM-011',
    scenarioId: 'epic-fury',
    headline: 'IRGC Navy: Strait of Hormuz mined — all shipping must cease immediately',
    body: 'IRGC Navy issues ultimatum that Strait of Hormuz has been mined and all commercial shipping must halt. Threatens to sink any vessel attempting transit. Oil prices spike 40% within an hour.',
    mediaType: 'official',
    infoEventType: 'disinfo_state',
    misinfoTaxonomy: ['misleading_framing', 'emotional_manipulation'],
    truthScore: 35,
    severityTier: 'critical',
    origin: { lat: 27.18, lon: 56.27 },
    targetLocation: { lat: 26.5, lon: 56.3 },
    propagationRadius: 600,
    timestamp: '2026-03-01T08:00:00Z',
    peakTimestamp: '2026-03-01T12:00:00Z',
    source: {
      name: 'IRGC Navy',
      type: 'state_official',
      country: 'IR',
      credibilityRating: 20,
      isStateAffiliated: true,
      platform: 'website',
      knownFor: 'Iranian Revolutionary Guard Corps Naval Forces',
    },
    amplifiers: [],
    linkedGroundTruthEventId: 'M-001',
    propagation: {
      speed: 'explosive',
      pattern: 'state_broadcast',
      peakVelocity: 20000,
      halfLife: 12,
      crossPlatformHops: 5,
    },
    reach: {
      estimatedImpressions: 100000000,
      shares: 350000,
      engagementRate: 0.05,
      countriesReached: ['IR', 'US', 'SA', 'AE', 'GB', 'JP', 'KR', 'CN', 'IN'],
      languagesSpread: ['fa', 'en', 'ar', 'ja', 'zh'],
    },
    verificationStatus: 'partly_true',
    groundTruthSummary: 'Some mines were detected in the strait, but US Navy minesweepers confirmed the mining was limited to a small area. The strait was never fully closed. IRGC exaggerated the threat to cause economic panic.',
    evidenceLinks: [],
  },

  // CLM-012: Beirut footage passed as Tehran
  {
    id: 'CLM-012',
    scenarioId: 'epic-fury',
    headline: 'Shocking: entire Tehran neighborhood destroyed — hundreds feared dead',
    body: 'Viral video showing massive building collapse and fires with caption claiming US strikes leveled a residential neighborhood in south Tehran. The video is real but is actually footage from the 2020 Beirut port explosion, not Tehran.',
    mediaType: 'video',
    infoEventType: 'misinfo_outdated',
    misinfoTaxonomy: ['manipulation', 'outdated', 'emotional_manipulation'],
    truthScore: 5,
    severityTier: 'high',
    origin: { lat: 34.0522, lon: -118.2437 },
    targetLocation: { lat: 35.6892, lon: 51.3890 },
    propagationRadius: 800,
    timestamp: '2026-02-28T08:42:00Z',
    source: {
      name: '@concerned_citizen_la',
      type: 'anonymous_account',
      country: 'US',
      credibilityRating: 10,
      isStateAffiliated: false,
      platform: 'twitter',
      followerCount: 2300,
    },
    amplifiers: [],
    propagation: {
      speed: 'fast',
      pattern: 'organic_viral',
      peakVelocity: 8000,
      halfLife: 6,
      crossPlatformHops: 3,
    },
    reach: {
      estimatedImpressions: 22000000,
      shares: 95000,
      engagementRate: 0.06,
      countriesReached: ['US', 'GB', 'CA', 'AU'],
      languagesSpread: ['en'],
    },
    verificationStatus: 'debunked',
    groundTruthSummary: 'Reverse image search confirms this is footage from the August 4, 2020 Beirut port explosion. No residential neighborhoods in Tehran were targeted in Operation Epic Fury strikes.',
    evidenceLinks: [
      {
        url: 'bellingcat.com/beirut-footage-misattributed',
        title: 'Old Beirut explosion footage circulating as Tehran strike',
        sourceReliability: 90,
        verdict: 'refutes',
        snippet: 'Frame-by-frame comparison with archived Beirut footage confirms identical source video.',
      },
    ],
  },

  // CLM-013: Khamenei assassination confirmation leak
  {
    id: 'CLM-013',
    scenarioId: 'epic-fury',
    headline: 'Unconfirmed: Senior Iranian leadership killed in targeted strike — Israeli operation',
    body: 'Israeli media citing unnamed military sources report that a separate Israeli strike killed Supreme Leader Khamenei during a meeting at his compound. No official confirmation from either Israel or Iran. Iranian state media silent on the topic.',
    mediaType: 'article',
    infoEventType: 'verification',
    misinfoTaxonomy: ['missing_context'],
    truthScore: 85,
    severityTier: 'critical',
    origin: { lat: 32.0853, lon: 34.7818 },
    targetLocation: { lat: 35.70, lon: 51.42 },
    propagationRadius: 2000,
    timestamp: '2026-02-28T08:00:00Z',
    peakTimestamp: '2026-02-28T16:00:00Z',
    source: {
      name: 'Channel 12 News (Israel)',
      type: 'legacy_media',
      country: 'IL',
      credibilityRating: 60,
      isStateAffiliated: false,
      platform: 'tv',
      knownFor: 'Major Israeli commercial TV network with strong military sources',
    },
    amplifiers: [],
    linkedGroundTruthEventId: 'K-007',
    propagation: {
      speed: 'explosive',
      pattern: 'influencer_cascade',
      peakVelocity: 35000,
      halfLife: 24,
      crossPlatformHops: 6,
    },
    reach: {
      estimatedImpressions: 180000000,
      shares: 500000,
      engagementRate: 0.07,
      countriesReached: ['IL', 'US', 'GB', 'FR', 'DE', 'SA', 'AE', 'IR'],
      languagesSpread: ['he', 'en', 'ar', 'fa'],
    },
    verificationStatus: 'confirmed',
    groundTruthSummary: 'Confirmed accurate. Israeli F-35I strike on Khamenei compound killed the Supreme Leader during a meeting, as confirmed by HUMINT intelligence. Iran did not officially acknowledge for 48 hours.',
    evidenceLinks: [],
  },

  // CLM-014: Hospital damage narrative weaponized
  {
    id: 'CLM-014',
    scenarioId: 'epic-fury',
    headline: 'Iranian Red Crescent: 200+ dead at Al Zahra Hospital — US deliberately targeted medical facility',
    body: 'Iranian Red Crescent Society claims Al Zahra Hospital in Isfahan was deliberately targeted. Images show significant structural damage. Iranian state media runs continuous coverage of hospital casualties.',
    mediaType: 'broadcast',
    infoEventType: 'disinfo_state',
    misinfoTaxonomy: ['misleading_framing', 'emotional_manipulation', 'cherry_picked'],
    truthScore: 30,
    severityTier: 'critical',
    origin: { lat: 32.68, lon: 51.67 },
    propagationRadius: 900,
    timestamp: '2026-03-01T10:30:00Z',
    peakTimestamp: '2026-03-01T18:00:00Z',
    source: {
      name: 'Iranian Red Crescent',
      type: 'ngo',
      country: 'IR',
      credibilityRating: 35,
      isStateAffiliated: true,
      platform: 'website',
      knownFor: 'Iranian Red Crescent Society — state-adjacent humanitarian org',
    },
    amplifiers: [],
    linkedGroundTruthEventId: 'C-002',
    propagation: {
      speed: 'fast',
      pattern: 'cross_platform_hop',
      peakVelocity: 12000,
      halfLife: 18,
      crossPlatformHops: 5,
    },
    reach: {
      estimatedImpressions: 60000000,
      shares: 250000,
      engagementRate: 0.06,
      countriesReached: ['IR', 'IQ', 'SY', 'LB', 'YE', 'RU', 'CN', 'TR'],
      languagesSpread: ['fa', 'ar', 'ru', 'zh', 'tr'],
    },
    verificationStatus: 'partly_true',
    groundTruthSummary: 'Hospital sustained real collateral damage from nearby strikes on nuclear infrastructure. However, the hospital was NOT directly targeted. Casualty figure is inflated — later independent assessment found ~50 casualties, not 200+.',
    evidenceLinks: [],
  },

  // CLM-015: Satire misread as real
  {
    id: 'CLM-015',
    scenarioId: 'epic-fury',
    headline: 'The Onion article shared as real: "Pentagon unveils new weapon that only destroys things that deserved it"',
    body: 'A satirical article from The Onion about US precision weapons being morally sentient is widely shared on social media as if real, with outraged commentary about American arrogance.',
    mediaType: 'article',
    infoEventType: 'satire_misread',
    misinfoTaxonomy: ['satire_misread'],
    truthScore: 0,
    severityTier: 'low',
    origin: { lat: 41.8781, lon: -87.6298 },
    propagationRadius: 400,
    timestamp: '2026-03-01T14:00:00Z',
    decayTimestamp: '2026-03-01T20:00:00Z',
    source: {
      name: 'The Onion',
      type: 'digital_native',
      country: 'US',
      credibilityRating: 0,
      isStateAffiliated: false,
      platform: 'website',
      knownFor: 'American satirical news publication',
    },
    amplifiers: [],
    propagation: {
      speed: 'steady',
      pattern: 'organic_viral',
      peakVelocity: 3000,
      halfLife: 4,
      crossPlatformHops: 2,
    },
    reach: {
      estimatedImpressions: 8000000,
      shares: 35000,
      engagementRate: 0.09,
      countriesReached: ['US', 'GB', 'CA'],
      languagesSpread: ['en'],
    },
    verificationStatus: 'satire',
    groundTruthSummary: 'The Onion is a well-known satirical publication. The article is clearly labeled as satire on its original page.',
    evidenceLinks: [],
  },
];

// ============================================================
// NARRATIVES
// ============================================================

export const EPIC_FURY_NARRATIVES: Narrative[] = [
  {
    id: 'NAR-001',
    scenarioId: 'epic-fury',
    title: 'Industrial accident, not military strike',
    summary: 'Iranian state media narrative claiming all explosions are industrial accidents at chemical/petrochemical plants with no nuclear or military connection.',
    linkedEventIds: ['K-002', 'K-003', 'K-004'],
    linkedClaimIds: ['CLM-001', 'CLM-003', 'CLM-005'],
    origin: 'state_manufactured',
    firstSeen: '2026-02-28T02:20:00Z',
    dominancePeriod: {
      start: '2026-02-28T02:20:00Z',
      end: '2026-02-28T06:00:00Z',
    },
    competingNarrativeIds: ['NAR-002', 'NAR-003'],
    truthAlignment: 5,
  },
  {
    id: 'NAR-002',
    scenarioId: 'epic-fury',
    title: 'Precision strikes on nuclear facilities — limited military operation',
    summary: 'US/coalition narrative of targeted strikes against Iranian nuclear weapons program infrastructure only, with no intent to strike civilian targets or pursue regime change.',
    linkedEventIds: ['K-002', 'K-003', 'K-004', 'K-006'],
    linkedClaimIds: ['CLM-002', 'CLM-004'],
    origin: 'media_consensus',
    firstSeen: '2026-02-28T03:00:00Z',
    dominancePeriod: {
      start: '2026-02-28T06:00:00Z',
      end: '2026-03-02T00:00:00Z',
    },
    competingNarrativeIds: ['NAR-001', 'NAR-003'],
    truthAlignment: 75,
  },
  {
    id: 'NAR-003',
    scenarioId: 'epic-fury',
    title: 'Unprovoked aggression — genocide against Iranian people',
    summary: 'Narrative framing the strikes as unprovoked Western aggression targeting civilians, amplified by bot networks and state-aligned influencers. Uses recycled footage from other conflicts as evidence of civilian casualties.',
    linkedEventIds: ['K-002'],
    linkedClaimIds: ['CLM-012', 'CLM-015', 'CLM-014'],
    origin: 'state_manufactured',
    firstSeen: '2026-02-28T04:30:00Z',
    competingNarrativeIds: ['NAR-001', 'NAR-002'],
    truthAlignment: 10,
  },
];

// ============================================================
// BOT NETWORKS
// ============================================================

export const EPIC_FURY_BOT_NETWORKS: BotNetwork[] = [
  {
    id: 'BOT-001',
    scenarioId: 'epic-fury',
    name: 'Tehran Echo Chamber',
    attributedTo: 'Iran — IRGC Cyber Command (assessed)',
    nodeCount: 1200,
    platforms: ['twitter', 'telegram', 'facebook'],
    primaryLocation: { lat: 35.6892, lon: 51.3890 },
    nodes: [
      { id: 'BN1-001', location: { lat: 35.70, lon: 51.42 }, platform: 'twitter', accountAge: 45, postFrequency: 12, connectedNodeIds: ['BN1-002', 'BN1-003'] },
      { id: 'BN1-002', location: { lat: 35.68, lon: 51.35 }, platform: 'twitter', accountAge: 30, postFrequency: 18, connectedNodeIds: ['BN1-001', 'BN1-004'] },
      { id: 'BN1-003', location: { lat: 35.72, lon: 51.40 }, platform: 'telegram', accountAge: 60, postFrequency: 8, connectedNodeIds: ['BN1-001'] },
      { id: 'BN1-004', location: { lat: 35.65, lon: 51.38 }, platform: 'facebook', accountAge: 22, postFrequency: 25, connectedNodeIds: ['BN1-002'] },
    ],
    activePeriod: {
      start: '2026-02-28T02:15:00Z',
      end: '2026-03-02T12:00:00Z',
    },
    targetClaimIds: ['CLM-001', 'CLM-003', 'CLM-010'],
    detectionConfidence: 78,
  },
  {
    id: 'BOT-002',
    scenarioId: 'epic-fury',
    name: 'St. Petersburg Troll Factory — Iran Support Cluster',
    attributedTo: 'Russia — IRA successor org (assessed)',
    nodeCount: 800,
    platforms: ['twitter', 'reddit', 'youtube'],
    primaryLocation: { lat: 59.9343, lon: 30.3351 },
    nodes: [
      { id: 'BN2-001', location: { lat: 59.94, lon: 30.32 }, platform: 'twitter', accountAge: 180, postFrequency: 6, connectedNodeIds: ['BN2-002'] },
      { id: 'BN2-002', location: { lat: 59.93, lon: 30.35 }, platform: 'reddit', accountAge: 90, postFrequency: 10, connectedNodeIds: ['BN2-001', 'BN2-003'] },
      { id: 'BN2-003', location: { lat: 59.95, lon: 30.30 }, platform: 'youtube', accountAge: 365, postFrequency: 3, connectedNodeIds: ['BN2-002'] },
    ],
    activePeriod: {
      start: '2026-02-28T03:00:00Z',
      end: '2026-03-02T18:00:00Z',
    },
    targetClaimIds: ['CLM-012', 'CLM-008', 'CLM-010'],
    detectionConfidence: 65,
  },
];

// ============================================================
// INFORMATION FOG ZONES
// ============================================================

export const EPIC_FURY_FOG_ZONES: InfoFogZone[] = [
  {
    id: 'FOG-001',
    scenarioId: 'epic-fury',
    name: 'Tehran Total Blackout',
    center: { lat: 35.6892, lon: 51.3890 },
    radiusKm: 80,
    fogLevel: 'total',
    cause: 'internet_shutdown',
    activePeriod: {
      start: '2026-02-28T02:30:00Z',
      end: '2026-03-01T14:00:00Z',
    },
    description: 'Complete internet and mobile communications shutdown across greater Tehran following initial strikes. No independent reporting possible.',
  },
  {
    id: 'FOG-002',
    scenarioId: 'epic-fury',
    name: 'Isfahan Information Void',
    center: { lat: 32.6546, lon: 51.6680 },
    radiusKm: 50,
    fogLevel: 'severe',
    cause: 'access_denied',
    activePeriod: {
      start: '2026-02-28T02:14:00Z',
      end: '2026-03-02T00:00:00Z',
    },
    description: 'IRGC security cordon established around Isfahan/Natanz strike zone. All journalists and civilians evacuated. No independent access.',
  },
  {
    id: 'FOG-003',
    scenarioId: 'epic-fury',
    name: 'Strait of Hormuz — Disinfo Saturation',
    center: { lat: 26.5667, lon: 56.2500 },
    radiusKm: 150,
    fogLevel: 'moderate',
    cause: 'disinfo_saturation',
    activePeriod: {
      start: '2026-03-01T06:00:00Z',
      end: '2026-03-02T18:00:00Z',
    },
    description: 'Conflicting claims about Strait of Hormuz status. Reports of mine deployment contradict shipping AIS data. Multiple false tanker-attack claims.',
  },
];
